### ISSUE TITLE
Error management - Implement missing error management

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/liteflow-js#4]
Here is a list of files that have some error management missing. There might be others that are harder to find through codebase search but that should be the jist of it:

**try/catch:**

- [ ] packages/hooks/src/useAcceptAuction.ts
- [ ] packages/hooks/src/useAcceptOffer.ts (3 occurences)
- [ ] packages/hooks/src/useActivateWallet.ts
- [ ] packages/hooks/src/useCancelOffer.ts
- [ ] packages/hooks/src/useCreateNFT.ts (seems like this one is checking for errors in the 'try', maybe check if need to do a catch as well)
- [ ] packages/hooks/src/useUpdateAccount.ts (seems like this one is also doing some error checking, check if need to catch as well)

**promises:**

- [ ] packages/email-connector/src/index.ts (2 occurences)
- [ ] packages/hooks/src/useAcceptOffer.ts
- [ ] packages/hooks/src/useCreateOffer.ts

**Comment by NicolasMahe** [comment]
The error management to display the error to the user should always be done in the **components**, never in a hook.

Hooks should produce and throw errors to parent functions until it reaches the component that is trigger the whole stuff in the first place.

So the whole hooks are already managing the error correctly:
- packages/hooks/src/useAcceptAuction.ts
- packages/hooks/src/useAcceptOffer.ts
- packages/hooks/src/useActivateWallet.ts
- packages/hooks/src/useCancelOffer.ts
- packages/hooks/src/useCreateNFT.ts
- packages/hooks/src/useUpdateAccount.ts

Also the following file are correct has they should only produce errors:
- packages/email-connector/src/index.ts

**Comment by NicolasMahe** [comment]
Also I randomly check the file `apps/weentar/components/organisms/Post/Offer/BidListItem.tsx` and the error management is done by a parent component:
https://github.com/liteflow-labs/nft/blob/5df7e3c347a43cfb81ed8efb38c0727bdc88034c/apps/weentar/pages/users/%5BuserId%5D/posts/%5BpostId%5D/index.tsx#L233-L244

I think any place where a `try finally` has been implemented is managing the error correctly (to confirm one by one of course). I would think the dev that choose to do a `try finally` instead of a `try catch finally` had good reason!

---

I think the best way to find places in the code where error management are missing will be to check for function defined using `useCallback` that directly call a function from a hook (`useXXX`).
One way could be to check where every hooks from the `hooks` package are used and check for error management.

**Comment by EmmanuelDrouin** [comment]
Idea is tracked here https://trello.com/c/351LtSSN/72-error-management-additional-implementation closing this issue for now as the discussion needs to move to Trello

**Comment by EmmanuelDrouin** [comment]
Re-opening as this is necessary and should be categorized as "bug"

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error management - Implement missing error management](https://trello.com/c/be3A0K0j/60-error-management-implement-missing-error-management)

**Comment by antho1404** [comment]
Closing this as only the hooks are left and as described here https://github.com/liteflow-labs/liteflow-js/issues/4#issuecomment-1291725717 the hooks is correctly handling errors
