### ISSUE TITLE
Cli cannot stop running services

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#57]
When stopping the command `dev`, the cli seems to not be able to stop the services.
There is no error returned.
The runner seems to have been deleted from the blockchain because the service's logs shows this error:
```
(node:1) UnhandledPromiseRejectionWarning: Error: 2 UNKNOWN: invalid request: runner "9n23UE9qXPmoRsLDTFrLJr79GH678vRgJsmJJEAhmB39" not found
```

here is the log of the cli:
```
  ✔ Starting environment
  ✔ Compiling processes
  ✔ Creating services
  ✔ Starting services
  ✔ Creating processes
  ✔ Fetching logs
[test][node-1] - 6gdEbdhG4mTk7rCoVsMGPZkJbURPkDeyhVRBYFeH6JFx - execute
	inputs:  {"code":"module.export = function(value) { return true }","inputs":{"foo":42}}
	outputs: {"result":true}

[test][node-1] - 6gdEbdhG4mTk7rCoVsMGPZkJbURPkDeyhVRBYFeH6JFx - execute
	inputs:  {"code":"module.export = function(value) { return true }","inputs":{"foo":42}}
	outputs: {"result":true}

[test][node-1] - 6gdEbdhG4mTk7rCoVsMGPZkJbURPkDeyhVRBYFeH6JFx - execute
	inputs:  {"inputs":{"foo":42},"code":"module.export = function(value) { return true }"}
	outputs: {"result":true}

[test][node-1] - 6gdEbdhG4mTk7rCoVsMGPZkJbURPkDeyhVRBYFeH6JFx - execute
	inputs:  {"inputs":{"foo":42},"code":"module.export = function(value) { return true }"}
	outputs: {"result":true}

[test][node-1] - 6gdEbdhG4mTk7rCoVsMGPZkJbURPkDeyhVRBYFeH6JFx - execute
	inputs:  {"inputs":{"foo":42},"code":"module.export = function(value) { return true }"}
	outputs: {"result":true}

^C ›   Warning: Result stream error: 1 CANCELLED: Cancelled
  ✔ Stopping logs
  ❯ Stopping running services
    ⠦ 9n23UE9qXPmoRsLDTFrLJr79GH678vRgJsmJJEAhmB39
      6rYzXT2h3hRyp6M6wbxxX3XUTzDQmar1xJNqsdVqUMdx
    Deleting processes
    Stopping environment
```

the container after the previous command stop:
```
➜  liteflow-js git:(master) docker ps -a
CONTAINER ID        IMAGE                                                   COMMAND             CREATED             STATUS                            PORTS                                              NAMES
498d9a88a1b7        liteflow:6uyKB5ibTJ9iVSxtYWShmGAcx13A5w5unj5rDAW9kLnh   "node index.js"     2 minutes ago       Up 2 minutes                                                                         liteflow_srv_6rYzXT2h3hRyp6M6wbxxX3XUTzDQmar1xJNqsdVqUMdx
1e026a34ac2d        liteflow:7eUQFthNEMXhh3gcSc4QujbuauFqKCovzgzaQDyiM2nX   "node index.js"     2 minutes ago       Exited (137) About a minute ago                                                      liteflow_srv_9n23UE9qXPmoRsLDTFrLJr79GH678vRgJsmJJEAhmB39
4f4b5830f205        mesg/engine:v0.22.0                                     "./engine"          3 minutes ago       Up 3 minutes                      0.0.0.0:1317->1317/tcp, 0.0.0.0:50052->50052/tcp   mesg_engine
```

**Comment by NicolasMahe** [comment]
The service used is https://github.com/liteflow-services/emit-event-interval

**Comment by antho1404** [comment]
I can reproduce and from the first investigations it looks like the issue come from this line
https://github.com/liteflow-labs/liteflow-js/blob/33d2d4eef1bd40306b48ba1c629a870a95e09fa7/packages/runner/src/providers/container/index.ts#L118
This is never resolved and no error seems to be thrown.

Direction for debug:
- This might come from the docker modem library that is buggy
- We probably use the wrong API docker has a `/container/xxx/wait` API (https://docs.docker.com/engine/api/v1.40/#operation/ContainerWait)
- There is a missing try/catch (try/catch in the command itself doesn't catch the error)

**Comment by antho1404** [comment]
This issue is apparently coming from the query to the engine 
https://github.com/liteflow-labs/liteflow-js/blob/143b67f2cfe29fc2e6bab660eb8ddaba24ef8d27/packages/runner/src/index.ts#L57

Not sure if this is related to node-fetch, or the engine.

Debug process:
- It seems that the stop command doesn't even reach docker API. Not in any of the docker logs
  - path: /Users/antho/Library/Containers/com.docker.docker/Data/log/host/
  - com.docker.backend.log
  - com.docker.supervisor.log
  - com.docker.driver.amd64-linux.log
  - vpnkit-bridge.log
- `docker event` receives nothing
- manual `docker stop` hits docker API and docker event
- stop for the engine seems to work fine (different config makes the API "ignore" the request?)
- We don't even arrive to the docker communication

**Comment by antho1404** [comment]
New progress:
The issue comes from this PR https://github.com/liteflow-labs/liteflow-js/pull/35. Without the capture of the process exit by this library, everything works fine even with the `container.stop()`.
My guess: The process exits, it is captured by the CLI but not only, probably by node as well or the library that handles HTTP requests and this HTTP handler force to exit the process. This might explain why I had some "random" issue with the runner query that doesn't work (in debug so a bit slower and so it breaks on a previous instruction).
This is just a guess for now but removing this interceptor of the process exits fix the issue.
